version: "3.8"

services:
  app:
    build: .
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src/public:/var/www/app/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
